var customers = [
  {
    firstName: "Raymond",
    lastName: "Keebler",
    randomEmail: "Granville_Hilpert39@hotmail.com",
    product: "Shirt",
    price: "954.00",
  },
  {
    firstName: "Cara",
    lastName: "Larson",
    randomEmail: "Dulce.Bashirian@yahoo.com",
    product: "Tuna",
    price: "382.00",
  },
  {
    firstName: "Anastacio",
    lastName: "Berge",
    randomEmail: "Ashleigh.Lehner@yahoo.com",
    product: "Fish",
    price: "39.00",
  },
  {
    firstName: "Danielle",
    lastName: "McDermott",
    randomEmail: "Aniyah_Gerlach@yahoo.com",
    product: "Chicken",
    price: "610.00",
  },
  {
    firstName: "Danika",
    lastName: "Bailey",
    randomEmail: "Kade42@yahoo.com",
    product: "Chips",
    price: "150.00",
  },
  {
    firstName: "Sandy",
    lastName: "Gislason",
    randomEmail: "Vincenzo_Koepp@yahoo.com",
    product: "Bacon",
    price: "823.00",
  },
  {
    firstName: "Pearlie",
    lastName: "Kris",
    randomEmail: "Preston53@gmail.com",
    product: "Fish",
    price: "973.00",
  },
  {
    firstName: "Bonita",
    lastName: "Goyette",
    randomEmail: "Cleta.Collier@hotmail.com",
    product: "Towels",
    price: "284.00",
  },
  {
    firstName: "Phyllis",
    lastName: "Carroll",
    randomEmail: "Maritza98@gmail.com",
    product: "Gloves",
    price: "369.00",
  },
  {
    firstName: "Jesse",
    lastName: "Bechtelar",
    randomEmail: "Nico_Roob21@hotmail.com",
    product: "Mouse",
    price: "424.00",
  },
  {
    firstName: "Owen",
    lastName: "Dietrich",
    randomEmail: "Jadon_Hoeger26@yahoo.com",
    product: "Pants",
    price: "914.00",
  },
  {
    firstName: "Antwan",
    lastName: "Bartell",
    randomEmail: "Sheldon.Miller@gmail.com",
    product: "Chair",
    price: "616.00",
  },
  {
    firstName: "Constantin",
    lastName: "Halvorson",
    randomEmail: "Carey44@yahoo.com",
    product: "Soap",
    price: "785.00",
  },
  {
    firstName: "Daron",
    lastName: "Swaniawski",
    randomEmail: "Ryann.Legros@hotmail.com",
    product: "Bacon",
    price: "66.00",
  },
  {
    firstName: "Johnny",
    lastName: "Baumbach",
    randomEmail: "Joesph_Green@yahoo.com",
    product: "Keyboard",
    price: "830.00",
  },
  {
    firstName: "Cristobal",
    lastName: "Conroy",
    randomEmail: "Columbus17@yahoo.com",
    product: "Shirt",
    price: "760.00",
  },
  {
    firstName: "Lonzo",
    lastName: "Lang",
    randomEmail: "Krystina9@gmail.com",
    product: "Computer",
    price: "832.00",
  },
  {
    firstName: "Conrad",
    lastName: "Gleichner",
    randomEmail: "Adalberto.Price59@yahoo.com",
    product: "Gloves",
    price: "904.00",
  },
  {
    firstName: "Bertram",
    lastName: "Monahan",
    randomEmail: "Jacey.Daugherty@gmail.com",
    product: "Shirt",
    price: "959.00",
  },
  {
    firstName: "Trever",
    lastName: "Price",
    randomEmail: "Georgianna_Hegmann@yahoo.com",
    product: "Bacon",
    price: "964.00",
  },
  {
    firstName: "Lilliana",
    lastName: "Hills",
    randomEmail: "Tianna_Bayer72@gmail.com",
    product: "Chips",
    price: "416.00",
  },
  {
    firstName: "Ike",
    lastName: "McLaughlin",
    randomEmail: "Elta.OConnell55@gmail.com",
    product: "Sausages",
    price: "946.00",
  },
  {
    firstName: "Kathlyn",
    lastName: "Harber",
    randomEmail: "Alexane_Cummings56@gmail.com",
    product: "Tuna",
    price: "283.00",
  },
  {
    firstName: "Candelario",
    lastName: "Bartoletti",
    randomEmail: "Aaron.Murray57@yahoo.com",
    product: "Bike",
    price: "391.00",
  },
  {
    firstName: "Reagan",
    lastName: "Lueilwitz",
    randomEmail: "Rosamond.Schroeder@yahoo.com",
    product: "Fish",
    price: "894.00",
  },
  {
    firstName: "Misael",
    lastName: "Fadel",
    randomEmail: "Kendrick.Pacocha@yahoo.com",
    product: "Tuna",
    price: "519.00",
  },
  {
    firstName: "Favian",
    lastName: "Gislason",
    randomEmail: "Darrell_Zboncak@gmail.com",
    product: "Chair",
    price: "883.00",
  },
  {
    firstName: "Serenity",
    lastName: "Hansen",
    randomEmail: "Skyla_Treutel44@hotmail.com",
    product: "Soap",
    price: "985.00",
  },
];

exports.customers = customers;
